builder: stop when gpg has not verified (#5)
* provided default functions when not using gpg

* refuse to create new sums unless gpg verified

* refuse to verify unless gpg verified

diff --git a/alpine-aports/abuild.patch b/alpine-aports/abuild.patch
--- a/alpine-aports/abuild.patch
+++ b/alpine-aports/abuild.patch
@@ -50,14 +50,16 @@
  
  	[ -z "$source" ] && return 0
  	fetch
-+	gpg_verify
++	gpg_verify || die "Failed to verify with GPG!"
  	for s in $source; do
  		files="$files $(filename_from_uri $s)"
  	done
-@@ -2460,6 +2466,10 @@
+@@ -2460,6 +2466,12 @@
  	fi
  }
  
++fetch_gpg_signatures() { :; }
++gpg_verify() { :; }
 +if [ -f "${sharedir}/gpg_signatures.sh" ]; then
 +        . "${sharedir}/gpg_signatures.sh"
 +fi
